//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilitera.Net.Comunicacao_Dash2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.ilitera.net.br/essence_hom", ConfigurationName="Comunicacao_Dash2.ComunicacaoDashSoap")]
    public interface ComunicacaoDashSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ilitera.net.br/essence_hom/Exposicao_Colaboradores", ReplyAction="*")]
        Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresResponse Exposicao_Colaboradores(Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="https://www.ilitera.net.br/essence_hom/Exposicao_Colaboradores", ReplyAction="*")]
        System.IAsyncResult BeginExposicao_Colaboradores(Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresRequest request, System.AsyncCallback callback, object asyncState);
        
        Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresResponse EndExposicao_Colaboradores(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ilitera.net.br/essence_hom/solicitar_CAT", ReplyAction="*")]
        Ilitera.Net.Comunicacao_Dash2.solicitar_CATResponse solicitar_CAT(Ilitera.Net.Comunicacao_Dash2.solicitar_CATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="https://www.ilitera.net.br/essence_hom/solicitar_CAT", ReplyAction="*")]
        System.IAsyncResult Beginsolicitar_CAT(Ilitera.Net.Comunicacao_Dash2.solicitar_CATRequest request, System.AsyncCallback callback, object asyncState);
        
        Ilitera.Net.Comunicacao_Dash2.solicitar_CATResponse Endsolicitar_CAT(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Exposicao_ColaboradoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Exposicao_Colaboradores", Namespace="https://www.ilitera.net.br/essence_hom", Order=0)]
        public Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresRequestBody Body;
        
        public Exposicao_ColaboradoresRequest() {
        }
        
        public Exposicao_ColaboradoresRequest(Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.ilitera.net.br/essence_hom")]
    public partial class Exposicao_ColaboradoresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CNPJ;
        
        public Exposicao_ColaboradoresRequestBody() {
        }
        
        public Exposicao_ColaboradoresRequestBody(string CNPJ) {
            this.CNPJ = CNPJ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Exposicao_ColaboradoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Exposicao_ColaboradoresResponse", Namespace="https://www.ilitera.net.br/essence_hom", Order=0)]
        public Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresResponseBody Body;
        
        public Exposicao_ColaboradoresResponse() {
        }
        
        public Exposicao_ColaboradoresResponse(Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.ilitera.net.br/essence_hom")]
    public partial class Exposicao_ColaboradoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement Exposicao_ColaboradoresResult;
        
        public Exposicao_ColaboradoresResponseBody() {
        }
        
        public Exposicao_ColaboradoresResponseBody(System.Xml.Linq.XElement Exposicao_ColaboradoresResult) {
            this.Exposicao_ColaboradoresResult = Exposicao_ColaboradoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitar_CATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="solicitar_CAT", Namespace="https://www.ilitera.net.br/essence_hom", Order=0)]
        public Ilitera.Net.Comunicacao_Dash2.solicitar_CATRequestBody Body;
        
        public solicitar_CATRequest() {
        }
        
        public solicitar_CATRequest(Ilitera.Net.Comunicacao_Dash2.solicitar_CATRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.ilitera.net.br/essence_hom")]
    public partial class solicitar_CATRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CNPJ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Colaborador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Data_Inicial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Data_Final;
        
        public solicitar_CATRequestBody() {
        }
        
        public solicitar_CATRequestBody(string ID, string CNPJ, string CodUsuario, string Colaborador, string Data_Inicial, string Data_Final) {
            this.ID = ID;
            this.CNPJ = CNPJ;
            this.CodUsuario = CodUsuario;
            this.Colaborador = Colaborador;
            this.Data_Inicial = Data_Inicial;
            this.Data_Final = Data_Final;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitar_CATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="solicitar_CATResponse", Namespace="https://www.ilitera.net.br/essence_hom", Order=0)]
        public Ilitera.Net.Comunicacao_Dash2.solicitar_CATResponseBody Body;
        
        public solicitar_CATResponse() {
        }
        
        public solicitar_CATResponse(Ilitera.Net.Comunicacao_Dash2.solicitar_CATResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.ilitera.net.br/essence_hom")]
    public partial class solicitar_CATResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement solicitar_CATResult;
        
        public solicitar_CATResponseBody() {
        }
        
        public solicitar_CATResponseBody(System.Xml.Linq.XElement solicitar_CATResult) {
            this.solicitar_CATResult = solicitar_CATResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComunicacaoDashSoapChannel : Ilitera.Net.Comunicacao_Dash2.ComunicacaoDashSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Exposicao_ColaboradoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Exposicao_ColaboradoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class solicitar_CATCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public solicitar_CATCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Ilitera.Net.Comunicacao_Dash2.solicitar_CATResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Ilitera.Net.Comunicacao_Dash2.solicitar_CATResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComunicacaoDashSoapClient : System.ServiceModel.ClientBase<Ilitera.Net.Comunicacao_Dash2.ComunicacaoDashSoap>, Ilitera.Net.Comunicacao_Dash2.ComunicacaoDashSoap {
        
        private BeginOperationDelegate onBeginExposicao_ColaboradoresDelegate;
        
        private EndOperationDelegate onEndExposicao_ColaboradoresDelegate;
        
        private System.Threading.SendOrPostCallback onExposicao_ColaboradoresCompletedDelegate;
        
        private BeginOperationDelegate onBeginsolicitar_CATDelegate;
        
        private EndOperationDelegate onEndsolicitar_CATDelegate;
        
        private System.Threading.SendOrPostCallback onsolicitar_CATCompletedDelegate;
        
        public ComunicacaoDashSoapClient() {
        }
        
        public ComunicacaoDashSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComunicacaoDashSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComunicacaoDashSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComunicacaoDashSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<Exposicao_ColaboradoresCompletedEventArgs> Exposicao_ColaboradoresCompleted;
        
        public event System.EventHandler<solicitar_CATCompletedEventArgs> solicitar_CATCompleted;
        
        public Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresResponse Exposicao_Colaboradores(Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresRequest request) {
            return base.Channel.Exposicao_Colaboradores(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginExposicao_Colaboradores(Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExposicao_Colaboradores(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresResponse EndExposicao_Colaboradores(System.IAsyncResult result) {
            return base.Channel.EndExposicao_Colaboradores(result);
        }
        
        private System.IAsyncResult OnBeginExposicao_Colaboradores(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresRequest request = ((Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresRequest)(inValues[0]));
            return this.BeginExposicao_Colaboradores(request, callback, asyncState);
        }
        
        private object[] OnEndExposicao_Colaboradores(System.IAsyncResult result) {
            Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresResponse retVal = this.EndExposicao_Colaboradores(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExposicao_ColaboradoresCompleted(object state) {
            if ((this.Exposicao_ColaboradoresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Exposicao_ColaboradoresCompleted(this, new Exposicao_ColaboradoresCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Exposicao_ColaboradoresAsync(Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresRequest request) {
            this.Exposicao_ColaboradoresAsync(request, null);
        }
        
        public void Exposicao_ColaboradoresAsync(Ilitera.Net.Comunicacao_Dash2.Exposicao_ColaboradoresRequest request, object userState) {
            if ((this.onBeginExposicao_ColaboradoresDelegate == null)) {
                this.onBeginExposicao_ColaboradoresDelegate = new BeginOperationDelegate(this.OnBeginExposicao_Colaboradores);
            }
            if ((this.onEndExposicao_ColaboradoresDelegate == null)) {
                this.onEndExposicao_ColaboradoresDelegate = new EndOperationDelegate(this.OnEndExposicao_Colaboradores);
            }
            if ((this.onExposicao_ColaboradoresCompletedDelegate == null)) {
                this.onExposicao_ColaboradoresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExposicao_ColaboradoresCompleted);
            }
            base.InvokeAsync(this.onBeginExposicao_ColaboradoresDelegate, new object[] {
                        request}, this.onEndExposicao_ColaboradoresDelegate, this.onExposicao_ColaboradoresCompletedDelegate, userState);
        }
        
        public Ilitera.Net.Comunicacao_Dash2.solicitar_CATResponse solicitar_CAT(Ilitera.Net.Comunicacao_Dash2.solicitar_CATRequest request) {
            return base.Channel.solicitar_CAT(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginsolicitar_CAT(Ilitera.Net.Comunicacao_Dash2.solicitar_CATRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginsolicitar_CAT(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Ilitera.Net.Comunicacao_Dash2.solicitar_CATResponse Endsolicitar_CAT(System.IAsyncResult result) {
            return base.Channel.Endsolicitar_CAT(result);
        }
        
        private System.IAsyncResult OnBeginsolicitar_CAT(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Ilitera.Net.Comunicacao_Dash2.solicitar_CATRequest request = ((Ilitera.Net.Comunicacao_Dash2.solicitar_CATRequest)(inValues[0]));
            return this.Beginsolicitar_CAT(request, callback, asyncState);
        }
        
        private object[] OnEndsolicitar_CAT(System.IAsyncResult result) {
            Ilitera.Net.Comunicacao_Dash2.solicitar_CATResponse retVal = this.Endsolicitar_CAT(result);
            return new object[] {
                    retVal};
        }
        
        private void Onsolicitar_CATCompleted(object state) {
            if ((this.solicitar_CATCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.solicitar_CATCompleted(this, new solicitar_CATCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void solicitar_CATAsync(Ilitera.Net.Comunicacao_Dash2.solicitar_CATRequest request) {
            this.solicitar_CATAsync(request, null);
        }
        
        public void solicitar_CATAsync(Ilitera.Net.Comunicacao_Dash2.solicitar_CATRequest request, object userState) {
            if ((this.onBeginsolicitar_CATDelegate == null)) {
                this.onBeginsolicitar_CATDelegate = new BeginOperationDelegate(this.OnBeginsolicitar_CAT);
            }
            if ((this.onEndsolicitar_CATDelegate == null)) {
                this.onEndsolicitar_CATDelegate = new EndOperationDelegate(this.OnEndsolicitar_CAT);
            }
            if ((this.onsolicitar_CATCompletedDelegate == null)) {
                this.onsolicitar_CATCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onsolicitar_CATCompleted);
            }
            base.InvokeAsync(this.onBeginsolicitar_CATDelegate, new object[] {
                        request}, this.onEndsolicitar_CATDelegate, this.onsolicitar_CATCompletedDelegate, userState);
        }
    }
}
